//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class bannnk
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string mname { get; set; }
        public string lname { get; set; }
        public string address { get; set; }
        public string gender { get; set; }
        public string marriagestat { get; set; }
        public string dobd { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string nationality { get; set; }
        public string rescon { get; set; }
        public string nice1 { get; set; }
        public string occupation { get; set; }
        public string nic1 { get; set; }
        public Nullable<decimal> balance { get; set; }
        public byte[] image { get; set; }
    }
}
